[dependencies]
base = "0.14.9"
devefi-icp-ledger = "../devefi_icp_ledger"
devefi-icrc-ledger = "../devefi_icrc_ledger"
account = "1.0.1"
stableheapbtreemap = "1.5.0"
itertools = "0.2.2"
rqq = "../rqq"